version: "3.8"

services:
  plochy_harvesine:
    image: smilecz/plochy_harvesine:latest
    container_name: plochy_harvesine
    restart: unless-stopped

    networks:
      - edge

    environment:
      - ACCESS_LOG_FILE=/logs/access.log
      - ANONYMIZE_IP=true
      - ACCESS_LOG_BUFFER_SIZE=1000
      - LOG_ROTATE_BYTES=10485760
      - LOG_ROTATE_MAX_FILES=5
      - LOG_ROTATE_CHECK_INTERVAL=60
      - LOG_ROTATE_MIN_INTERVAL_SECONDS=10

    volumes:
      - plochy_logs:/logs
      # Bind-mount local secret file when not using Swarm secrets
      - ./secrets/ip_hash_secret:/run/secrets/ip_hash_secret:ro

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=edge"

      - "traefik.http.routers.plochy.rule=Host(`plochy-harvesine.gearground.cloud`)"
      - "traefik.http.routers.plochy.entrypoints=websecure"
      - "traefik.http.routers.plochy.tls=true"
      - "traefik.http.routers.plochy.tls.certresolver=le"
      - "traefik.http.routers.plochy.priority=100"
      - "traefik.http.services.plochy.loadbalancer.server.port=80"

      - "traefik.http.routers.plochy_http.rule=Host(`plochy-harvesine.gearground.cloud`)"
      - "traefik.http.routers.plochy_http.entrypoints=web"
      - "traefik.http.routers.plochy_http.middlewares=plochy_https_redirect"
      - "traefik.http.middlewares.plochy_https_redirect.redirectscheme.scheme=https"

      - "traefik.http.routers.plochy.middlewares=plochy-errors-404@docker,plochy-errors-5xx@docker"

      - "traefik.http.middlewares.plochy-errors-404.errors.status=404"
      - "traefik.http.middlewares.plochy-errors-404.errors.service=error-pages-svc@docker"
      - "traefik.http.middlewares.plochy-errors-404.errors.query=/404.html"

      - "traefik.http.middlewares.plochy-errors-5xx.errors.status=500-599"
      - "traefik.http.middlewares.plochy-errors-5xx.errors.service=error-pages-svc@docker"
      - "traefik.http.middlewares.plochy-errors-5xx.errors.query=/error.html"

    deploy:
      resources:
        limits:
          memory: 32M


networks:
  edge:
    external: true

volumes:
  plochy_logs:
    name: plochy_logs

# NOTE: removed top-level `secrets:` section because this stack is intended
# to run without Docker Swarm secrets. If you *do* want to use Swarm secrets,
# restore the `secrets:` block and create the secret with `docker secret create`.
